// Mock data for development - replaces Firebase
export const mockColors = [
  {
    id: "1",
    name: "Ocean Blue",
    primary: "#0066CC",
    secondary: "#00B4D8",
    accent: "#CAF0F8",
  },
  {
    id: "2",
    name: "Sunset Orange",
    primary: "#FF6B35",
    secondary: "#F7931E",
    accent: "#FED766",
  },
  {
    id: "3",
    name: "Forest Green",
    primary: "#2D6A4F",
    secondary: "#40916C",
    accent: "#95D5B2",
  },
  {
    id: "4",
    name: "Purple Dream",
    primary: "#7209B7",
    secondary: "#B5179E",
    accent: "#F72585",
  },
  {
    id: "5",
    name: "Midnight Gray",
    primary: "#1F2937",
    secondary: "#4B5563",
    accent: "#9CA3AF",
  },
  {
    id: "6",
    name: "Cherry Red",
    primary: "#DC2626",
    secondary: "#EF4444",
    accent: "#FECACA",
  },
  {
    id: "7",
    name: "Teal Turquoise",
    primary: "#0D9488",
    secondary: "#14B8A6",
    accent: "#CCFBF1",
  },
  {
    id: "8",
    name: "Gold Luxury",
    primary: "#B8860B",
    secondary: "#DAA520",
    accent: "#FFD700",
  },
];

export const mockFonts = [
  {
    id: "1",
    name: "Serif Elegance",
    fontFamily: "Georgia, serif",
    weights: ["400", "700"],
    category: "serif",
  },
  {
    id: "2",
    name: "Modern Sans",
    fontFamily: "Helvetica, Arial, sans-serif",
    weights: ["400", "600", "700"],
    category: "sans-serif",
  },
  {
    id: "3",
    name: "Playful Display",
    fontFamily: "Comic Sans MS, cursive",
    weights: ["400", "700"],
    category: "display",
  },
  {
    id: "4",
    name: "Monospace Code",
    fontFamily: "Courier New, monospace",
    weights: ["400", "700"],
    category: "monospace",
  },
  {
    id: "5",
    name: "Clean Minimal",
    fontFamily: "Verdana, sans-serif",
    weights: ["400", "600"],
    category: "sans-serif",
  },
  {
    id: "6",
    name: "Script Handwriting",
    fontFamily: "Brush Script MT, cursive",
    weights: ["400"],
    category: "handwriting",
  },
  {
    id: "7",
    name: "Bold Statement",
    fontFamily: "Impact, sans-serif",
    weights: ["700", "900"],
    category: "display",
  },
  {
    id: "8",
    name: "Classic Text",
    fontFamily: "Times New Roman, serif",
    weights: ["400", "700"],
    category: "serif",
  },
];

export const mockIdeas = [
  {
    id: "1",
    title: "Mobile App Landing Page",
    description: "Design a landing page for a new mobile application",
    difficulty: "easy",
    type: "website",
  },
  {
    id: "2",
    title: "E-commerce Product Page",
    description: "Create a product showcase page for an online store",
    difficulty: "easy",
    type: "website",
  },
  {
    id: "3",
    title: "Blog Article Layout",
    description: "Design a blog post page with article content",
    difficulty: "easy",
    type: "website",
  },
  {
    id: "4",
    title: "SaaS Dashboard",
    description: "Design an analytics dashboard for a SaaS platform",
    difficulty: "medium",
    type: "dashboard",
  },
  {
    id: "5",
    title: "Social Media Feed",
    description: "Create a social media feed interface",
    difficulty: "medium",
    type: "website",
  },
  {
    id: "6",
    title: "Restaurant Menu Website",
    description: "Design a restaurant website with menu showcase",
    difficulty: "medium",
    type: "website",
  },
  {
    id: "7",
    title: "Real-time Collaboration Tool",
    description: "Build interface for team collaboration platform",
    difficulty: "hard",
    type: "dashboard",
  },
  {
    id: "8",
    title: "AI-Powered Search Interface",
    description: "Design an advanced search and discovery platform",
    difficulty: "hard",
    type: "website",
  },
  {
    id: "9",
    title: "Educational Platform",
    description: "Create a course management and learning system",
    difficulty: "hard",
    type: "dashboard",
  },
  {
    id: "10",
    title: "Business Cards",
    description: "Design professional business card layouts",
    difficulty: "easy",
    type: "print",
  },
  {
    id: "11",
    title: "Poster Design",
    description: "Create an eye-catching poster for marketing",
    difficulty: "medium",
    type: "print",
  },
  {
    id: "12",
    title: "Magazine Layout",
    description: "Design a magazine spread or cover",
    difficulty: "hard",
    type: "print",
  },
];

export const mockLayouts = [
  {
    id: "1",
    name: "Hero Section Layout",
    description: "Large hero image with text overlay",
    type: "website",
  },
  {
    id: "2",
    name: "Grid Product Layout",
    description: "3-column grid for product display",
    type: "website",
  },
  {
    id: "3",
    name: "Two Column Layout",
    description: "Content on left, image on right",
    type: "website",
  },
  {
    id: "4",
    name: "Dashboard Grid",
    description: "Customizable dashboard with cards",
    type: "dashboard",
  },
  {
    id: "5",
    name: "Data Visualization",
    description: "Charts and graph layout",
    type: "dashboard",
  },
  {
    id: "6",
    name: "Metrics Overview",
    description: "Key metrics and KPIs display",
    type: "dashboard",
  },
  {
    id: "7",
    name: "Standard Card",
    description: "3.5 x 2 inch business card",
    type: "print",
  },
  {
    id: "8",
    name: "Full Bleed Poster",
    description: "24 x 36 inch poster design",
    type: "print",
  },
  {
    id: "9",
    name: "Magazine Spread",
    description: "Double page magazine layout",
    type: "print",
  },
];

export const mockPersonas = [
  {
    id: "1",
    name: "Tech Startup Founder",
    age: 28,
    industry: "Technology",
    goals: ["Disrupt the market", "Build a unicorn", "Help entrepreneurs"],
    painPoints: ["Funding", "Team building", "Market validation"],
  },
  {
    id: "2",
    name: "Small Business Owner",
    age: 45,
    industry: "Retail",
    goals: ["Grow business", "Improve customer loyalty", "Increase sales"],
    painPoints: ["Competition", "Customer acquisition", "Operations"],
  },
  {
    id: "3",
    name: "Digital Marketer",
    age: 32,
    industry: "Marketing",
    goals: ["Drive engagement", "Increase conversions", "Build brand"],
    painPoints: ["Data analysis", "Tool complexity", "Attribution"],
  },
  {
    id: "4",
    name: "Creative Designer",
    age: 26,
    industry: "Design",
    goals: [
      "Create beautiful work",
      "Build portfolio",
      "Collaborate effectively",
    ],
    painPoints: ["Client feedback loops", "Version control", "Inspiration"],
  },
  {
    id: "5",
    name: "B2B Sales Manager",
    age: 38,
    industry: "Sales",
    goals: ["Hit targets", "Build relationships", "Improve pipeline"],
    painPoints: ["Lead quality", "Sales process", "Team motivation"],
  },
  {
    id: "6",
    name: "Product Manager",
    age: 35,
    industry: "Product",
    goals: [
      "Create user-centric products",
      "Grow user base",
      "Iterate quickly",
    ],
    painPoints: [
      "User research",
      "Stakeholder alignment",
      "Technical constraints",
    ],
  },
  {
    id: "7",
    name: "Content Creator",
    age: 24,
    industry: "Media",
    goals: ["Build audience", "Generate income", "Create engaging content"],
    painPoints: ["Consistency", "Algorithm changes", "Monetization"],
  },
  {
    id: "8",
    name: "Enterprise CTO",
    age: 50,
    industry: "Technology",
    goals: ["Digital transformation", "Reduce costs", "Improve security"],
    painPoints: ["Legacy systems", "Skills gap", "Budget constraints"],
  },
];
