// Mock data for development - replaces Firebase
export const mockColors = [
  {
    id: "1",
    name: "Ocean Blue",
    color1: "0066CC",
    color2: "00B4D8",
    color3: "CAF0F8",
    color4: "0084B4",
    color5: "E0F2FE",
  },
  {
    id: "2",
    name: "Sunset Orange",
    color1: "FF6B35",
    color2: "F7931E",
    color3: "FED766",
    color4: "FF8C42",
    color5: "FFE5CC",
  },
  {
    id: "3",
    name: "Forest Green",
    color1: "2D6A4F",
    color2: "40916C",
    color3: "95D5B2",
    color4: "52B788",
    color5: "D8F3DC",
  },
  {
    id: "4",
    name: "Purple Dream",
    color1: "7209B7",
    color2: "B5179E",
    color3: "F72585",
    color4: "C60EBE",
    color5: "F8D7FF",
  },
  {
    id: "5",
    name: "Midnight Gray",
    color1: "1F2937",
    color2: "4B5563",
    color3: "9CA3AF",
    color4: "6B7280",
    color5: "E5E7EB",
  },
  {
    id: "6",
    name: "Cherry Red",
    color1: "DC2626",
    color2: "EF4444",
    color3: "FECACA",
    color4: "F87171",
    color5: "FEE2E2",
  },
  {
    id: "7",
    name: "Teal Turquoise",
    color1: "0D9488",
    color2: "14B8A6",
    color3: "CCFBF1",
    color4: "2DD4BF",
    color5: "F0FDFA",
  },
  {
    id: "8",
    name: "Gold Luxury",
    color1: "B8860B",
    color2: "DAA520",
    color3: "FFD700",
    color4: "FFA500",
    color5: "FFFACD",
  },
];

export const mockFonts = [
  {
    id: "1",
    name: "Serif Elegance",
    fontFamily: "Georgia, serif",
    weights: ["400", "700"],
    category: "serif",
    title_font: "Playfair Display",
    title_link:
      "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700",
    paragraph_font: "Lora",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=Lora:wght@400;700",
  },
  {
    id: "2",
    name: "Modern Sans",
    fontFamily: "Helvetica, Arial, sans-serif",
    weights: ["400", "600", "700"],
    category: "sans-serif",
    title_font: "Inter",
    title_link:
      "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700",
    paragraph_font: "Inter",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700",
  },
  {
    id: "3",
    name: "Playful Display",
    fontFamily: "Comic Sans MS, cursive",
    weights: ["400", "700"],
    category: "display",
    title_font: "Poppins",
    title_link: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700",
    paragraph_font: "Poppins",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700",
  },
  {
    id: "4",
    name: "Monospace Code",
    fontFamily: "Courier New, monospace",
    weights: ["400", "700"],
    category: "monospace",
    title_font: "JetBrains Mono",
    title_link:
      "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700",
    paragraph_font: "JetBrains Mono",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700",
  },
  {
    id: "5",
    name: "Clean Minimal",
    fontFamily: "Verdana, sans-serif",
    weights: ["400", "600"],
    category: "sans-serif",
    title_font: "Roboto",
    title_link: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;600",
    paragraph_font: "Roboto",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=Roboto:wght@400;600",
  },
  {
    id: "6",
    name: "Script Handwriting",
    fontFamily: "Brush Script MT, cursive",
    weights: ["400"],
    category: "handwriting",
    title_font: "Great Vibes",
    title_link: "https://fonts.googleapis.com/css2?family=Great+Vibes:wght@400",
    paragraph_font: "Dancing Script",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400",
  },
  {
    id: "7",
    name: "Bold Statement",
    fontFamily: "Impact, sans-serif",
    weights: ["700", "900"],
    category: "display",
    title_font: "Montserrat",
    title_link:
      "https://fonts.googleapis.com/css2?family=Montserrat:wght@700;900",
    paragraph_font: "Montserrat",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=Montserrat:wght@700;900",
  },
  {
    id: "8",
    name: "Classic Text",
    fontFamily: "Times New Roman, serif",
    weights: ["400", "700"],
    category: "serif",
    title_font: "EB Garamond",
    title_link:
      "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;700",
    paragraph_font: "EB Garamond",
    paragraph_link:
      "https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;700",
  },
];

export const mockIdeas = [
  {
    id: "1",
    title: "Mobile App Landing Page",
    description: "Design a landing page for a new mobile application",
    difficulty: "easy",
    type: "website",
  },
  {
    id: "2",
    title: "E-commerce Product Page",
    description: "Create a product showcase page for an online store",
    difficulty: "easy",
    type: "website",
  },
  {
    id: "3",
    title: "Blog Article Layout",
    description: "Design a blog post page with article content",
    difficulty: "easy",
    type: "website",
  },
  {
    id: "4",
    title: "SaaS Dashboard",
    description: "Design an analytics dashboard for a SaaS platform",
    difficulty: "medium",
    type: "dashboard",
  },
  {
    id: "5",
    title: "Social Media Feed",
    description: "Create a social media feed interface",
    difficulty: "medium",
    type: "website",
  },
  {
    id: "6",
    title: "Restaurant Menu Website",
    description: "Design a restaurant website with menu showcase",
    difficulty: "medium",
    type: "website",
  },
  {
    id: "7",
    title: "Real-time Collaboration Tool",
    description: "Build interface for team collaboration platform",
    difficulty: "hard",
    type: "dashboard",
  },
  {
    id: "8",
    title: "AI-Powered Search Interface",
    description: "Design an advanced search and discovery platform",
    difficulty: "hard",
    type: "website",
  },
  {
    id: "9",
    title: "Educational Platform",
    description: "Create a course management and learning system",
    difficulty: "hard",
    type: "dashboard",
  },
  {
    id: "10",
    title: "Business Cards",
    description: "Design professional business card layouts",
    difficulty: "easy",
    type: "print",
  },
  {
    id: "11",
    title: "Poster Design",
    description: "Create an eye-catching poster for marketing",
    difficulty: "medium",
    type: "print",
  },
  {
    id: "12",
    title: "Magazine Layout",
    description: "Design a magazine spread or cover",
    difficulty: "hard",
    type: "print",
  },
];

export const mockLayouts = [
  {
    id: "1",
    name: "Hero Section Layout",
    description: "Large hero image with text overlay",
    type: "website",
  },
  {
    id: "2",
    name: "Grid Product Layout",
    description: "3-column grid for product display",
    type: "website",
  },
  {
    id: "3",
    name: "Two Column Layout",
    description: "Content on left, image on right",
    type: "website",
  },
  {
    id: "4",
    name: "Dashboard Grid",
    description: "Customizable dashboard with cards",
    type: "dashboard",
  },
  {
    id: "5",
    name: "Data Visualization",
    description: "Charts and graph layout",
    type: "dashboard",
  },
  {
    id: "6",
    name: "Metrics Overview",
    description: "Key metrics and KPIs display",
    type: "dashboard",
  },
  {
    id: "7",
    name: "Standard Card",
    description: "3.5 x 2 inch business card",
    type: "print",
  },
  {
    id: "8",
    name: "Full Bleed Poster",
    description: "24 x 36 inch poster design",
    type: "print",
  },
  {
    id: "9",
    name: "Magazine Spread",
    description: "Double page magazine layout",
    type: "print",
  },
];

export const mockPersonas = [
  {
    id: "1",
    name: "Tech Startup Founder",
    age: 28,
    industry: "Technology",
    sex: false,
    about:
      "Ambitious entrepreneur with a passion for innovation and building groundbreaking products in the tech space.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    goals: ["Disrupt the market", "Build a unicorn", "Help entrepreneurs"],
    painPoints: ["Funding", "Team building", "Market validation"],
  },
  {
    id: "2",
    name: "Small Business Owner",
    age: 45,
    industry: "Retail",
    sex: false,
    about:
      "Experienced business leader focused on growing a successful retail company with strong customer relationships.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=david",
    goals: ["Grow business", "Improve customer loyalty", "Increase sales"],
    painPoints: ["Competition", "Customer acquisition", "Operations"],
  },
  {
    id: "3",
    name: "Digital Marketer",
    age: 32,
    industry: "Marketing",
    sex: true,
    about:
      "Data-driven marketer with expertise in digital campaigns and engagement strategies across multiple channels.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    goals: ["Drive engagement", "Increase conversions", "Build brand"],
    painPoints: ["Data analysis", "Tool complexity", "Attribution"],
  },
  {
    id: "4",
    name: "Creative Designer",
    age: 26,
    industry: "Design",
    sex: true,
    about:
      "Talented designer passionate about creating visually stunning work and collaborating with talented teams.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
    goals: [
      "Create beautiful work",
      "Build portfolio",
      "Collaborate effectively",
    ],
    painPoints: ["Client feedback loops", "Version control", "Inspiration"],
  },
  {
    id: "5",
    name: "B2B Sales Manager",
    age: 38,
    industry: "Sales",
    sex: false,
    about:
      "Results-oriented sales leader with extensive experience in building and managing high-performing sales teams.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael",
    goals: ["Hit targets", "Build relationships", "Improve pipeline"],
    painPoints: ["Lead quality", "Sales process", "Team motivation"],
  },
  {
    id: "6",
    name: "Product Manager",
    age: 35,
    industry: "Product",
    sex: true,
    about:
      "Strategic thinker focused on delivering user-centric products and driving continuous innovation and iteration.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jessica",
    goals: [
      "Create user-centric products",
      "Grow user base",
      "Iterate quickly",
    ],
    painPoints: [
      "User research",
      "Stakeholder alignment",
      "Technical constraints",
    ],
  },
  {
    id: "7",
    name: "Content Creator",
    age: 24,
    industry: "Media",
    sex: true,
    about:
      "Energetic content creator with strong social media presence and passion for engaging audiences daily.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=olivia",
    goals: ["Build audience", "Generate income", "Create engaging content"],
    painPoints: ["Consistency", "Algorithm changes", "Monetization"],
  },
  {
    id: "8",
    name: "Enterprise CTO",
    age: 50,
    industry: "Technology",
    sex: false,
    about:
      "Seasoned technology executive leading digital transformation and modernizing legacy systems at scale.",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=robert",
    goals: ["Digital transformation", "Reduce costs", "Improve security"],
    painPoints: ["Legacy systems", "Skills gap", "Budget constraints"],
  },
];
